global:
  scrape_interval: 15s # Собирать метрики каждые 15 секунд

scrape_configs:
- job_name: 'MubaraK-AI-app'
  # Prometheus будет обращаться к сервису 'web' по порту 8000
  # и забирать данные с эндпоинта /metrics
  static_configs:
  - targets: [ 'web:8000' ]
